sudo: true
language: c
os:
  - linux
  #- osx
compiler:
  - gcc
  #- clang
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  # from http://askubuntu.com/questions/420991/install-autoconf-2-69-on-ubuntu-12-04/632769#632769
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - sh ./travis/install-deps.sh $MPI_IMPL
script:
  - sh ./travis/build-run.sh $MPI_IMPL
after_failure:
  - cat ./config.log
  - find . -name "*.log" -exec head -n 100 {} ";"
